### PR TITLE
Open informations links in new window

### PR DESCRIPTION
**Pull request by mathroc**
otherwise we can't go back to the app without closing it

### CODE REVIEW

**Comment by nicodel** [comment]
Thank you for this !

**Comment by nicodel** [comment]
After checking it, it seems not to be working. For some reason, `target="_blank"` is not taken into account. Maybe bricks is messing with the DOM.

**Comment by mathroc** [comment]
I could not reproduce the problem. it's working fine on 2.0 on my phone (Revolution). also tried 1.3 and 2.2 on simulator and it's working too. 
what version are you using ?

**Comment by Bonbadil** [comment]
Hello.
I've just tried on my OpenC with FFOS 1.3 and it's working.

**Comment by nicodel** [comment]
I tried you PR on a Firefox and on simulators 1.2 and 2.0. All got the same effects.
I did a workaround: adding the `target="_blank` only when the Settings view is called.

**Comment by mathroc** [comment]
oh I didn't noticed you added a workaround on develop. that's the branch I was testing it with. indeed without your workaround it does not works!

in fact target="_blank" does not appears in the DOM inspector. so yeah maybe it an issue with brick

**Comment by nicodel** [comment]
Issue filled in brick [#273] (https://github.com/mozbrick/brick/issues/273).
But project seems to be on hold since october... we'll see.

**Pull request merged**
